# Generated by Django 4.2.4 on 2023-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_provider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='additional_percent',
            field=models.PositiveIntegerField(verbose_name='Процент от прибыли'),
        ),
        migrations.AlterField(
            model_name='master',
            name='additional_percent',
            field=models.PositiveIntegerField(verbose_name='Процент от прибыли'),
        ),
    ]
