# Generated by Django 4.2.4 on 2023-09-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mulct_manager_mulcts_master_mulcts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mulct',
            options={'verbose_name': 'Штраф', 'verbose_name_plural': 'Штрафы'},
        ),
        migrations.AddField(
            model_name='mulct',
            name='name',
            field=models.CharField(default='test', max_length=128, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
