# Generated by Django 4.2.4 on 2023-09-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('rudder', models.CharField(choices=[('RIGHT', 'Правый'), ('LEFT', 'Левый')], max_length=8, verbose_name='Руль')),
                ('drive', models.CharField(choices=[('FULL', 'Полный привод'), ('BACK', 'Задний привод'), ('FRONT', 'Передний привод')], max_length=8, verbose_name='Вид привода')),
            ],
        ),
    ]
