# Generated by Django 4.2.4 on 2023-09-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклама'},
        ),
    ]
