# Generated by Django 4.2.4 on 2023-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_serviceorder_client_serviceorder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дополнительные расходы'),
            preserve_default=False,
        ),
    ]
