# Generated by Django 4.2.4 on 2023-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_options', '0001_initial'),
        ('orders', '0007_order_additional_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advanced_options',
            field=models.ManyToManyField(to='advanced_options.advancedoption'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='advanced_options',
            field=models.ManyToManyField(to='advanced_options.advancedoption'),
        ),
    ]
