# Generated by Django 4.2.4 on 2023-09-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_manager_additional_percent_and_more'),
        ('orders', '0008_order_advanced_options_serviceorder_advanced_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='manager',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.master', verbose_name='Мастер'),
        ),
    ]
