# Generated by Django 4.2.4 on 2023-09-13 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_amount'),
        ('advanced_options', '0001_initial'),
        ('users', '0003_alter_manager_additional_percent_and_more'),
        ('orders', '0009_remove_serviceorder_manager_serviceorder_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('advanced_options', models.ManyToManyField(to='advanced_options.advancedoption')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.manager', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
                ('provider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.provider', verbose_name='Поставщик')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Товар для продажи',
                'verbose_name_plural': 'Товары для продажи',
            },
        ),
    ]
