# Generated by Django 4.2.4 on 2023-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_supply',
            field=models.BooleanField(default=False, verbose_name='Под поставку'),
            preserve_default=False,
        ),
    ]
