# Generated by Django 4.2.4 on 2023-09-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_for_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForSupply',
            fields=[
            ],
            options={
                'verbose_name': 'Под поставку',
                'verbose_name_plural': 'Под поставку',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
