# Generated by Django 4.2.4 on 2023-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_options', '0001_initial'),
        ('products', '0004_productforsupply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='advanced_options',
            field=models.ManyToManyField(to='advanced_options.advancedoption'),
        ),
    ]
