# Generated by Django 4.2.4 on 2023-09-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_product_advanced_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTuning',
            fields=[
            ],
            options={
                'verbose_name': 'Тюнинг в наличии',
                'verbose_name_plural': 'Тюнинг в наличии',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductTuningForSupply',
            fields=[
            ],
            options={
                'verbose_name': 'Тюнинг под заказ',
                'verbose_name_plural': 'Тюнинг под заказ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Аксессуары в наличии'},
        ),
        migrations.AlterModelOptions(
            name='productforsupply',
            options={'verbose_name': 'Под поставку', 'verbose_name_plural': 'Аксессуары под заказ'},
        ),
    ]
