# Generated by Django 4.2.4 on 2023-09-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producttuning_producttuningforsupply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
